### ISSUE TITLE
Possibly not 32 bit compatible

### ISSUE THREAD

**Issue by jigenbakuda** [titinko/utsu#27]
I was running the program on my 32-bit desktop machine (linux) and it would not work. I installed it on a 64 bit machine (linux) and it did work. I am not sure exactly sure what the problem is, but it may be that it is not 32 bit compatible. I know a number of linux users work on older machines. So if it is the case that it does not work on 32 bit machines, I think you should clearly state that it is only compatible with 64 bit machines (especially for linux users).

Here is the terminal output when I tried to play utsu on my 32 bit machine.

> ES2 Prism: Error - GLX extension is not supported
>     GLX version 1.3 or higher is required
> Parsed voicebank as assets/voice/Iona_Beta
> assets/voice/Iona_Beta/mi.wav 0.0 227.5 111.5 120.4 101.4
> Length is 581.4
> assets/voice/Iona_Beta/mi.wav 0.0 227.5 111.5 120.4 101.4
> Length is 581.4
> assets/voice/Iona_Beta/mi.wav 0.0 227.5 111.5 120.4 101.4
> Length is 600.4
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: Syntax error: "(" unexpected
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: Syntax error: "(" unexpected
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/macres: Syntax error: "(" unexpected
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: Syntax error: Unterminated quoted string
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: Syntax error: Unterminated quoted string
> /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: 1: /home/jigenbakuda/Utsu/utsu-0.4/assets/linux64/wavtool-yawu: Syntax error: Unterminated quoted string
> Exception in thread "Thread-9" MediaException: MEDIA_UNAVAILABLE : /tmp/1580062806511-0/final_song.wav (No such file or directory)
> 	at javafx.scene.media.Media.<init>(Media.java:407)
> 	at com.utsusynth.utsu.engine.Engine.startPlayback(Engine.java:102)
> 	at com.utsusynth.utsu.controller.SongController.lambda$startPlayback$31(SongController.java:745)
> 	at java.lang.Thread.run(Thread.java:748)

This is off topic, but I do not think it deserves its own Issue thread, but in the instructions for using the jar file method of running the program the instructions need to be updated or clarified.

The code provides 
`

> cd /path/to/jarfile
> java -jar utsu-0.1-jfx.jar

`

but to run the current jar file it should have

> cd /path/to/jarfile
> java -jar utsu-0.4-jfx.jar`

Might I suggest an instruction like this that says you should replace X with the current number of release

> cd /path/to/jarfile
> java -jar utsu-0.X-jfx.jar

**Comment by optionis-jx** [comment]
The supporting tools, such as the resamper, used by UTSU are 64 bit only.

**Comment by titinko** [comment]
I will update the README.  I only have the 64 bit versions of each default resampler for now, but in theory the 32 bit versions can be added if I can build executables for them.  A workaround would be to switch the resampler/wavtools to a 32 bit version.  If you're familiar with compilers, you can try building new executables for macres and wavtool-yawu from their source code on GitHub.
